export const PERMISSIONS = [
  { key: "identity:user:create", description: "Create users" },
  { key: "identity:user:view", description: "View users" },
  { key: "identity:user:disable", description: "Disable users" },
  { key: "admin:manage_users", description: "Manage users" },
  { key: "admin:manage_roles", description: "Manage roles and role assignments" },
  { key: "admin:manage_policies", description: "Manage approval policies" },
  { key: "team:view", description: "View teams" },
  { key: "team:manage", description: "Create teams and memberships" },
  { key: "project:create", description: "Create projects" },
  { key: "project:view", description: "View projects" },
  { key: "artifact:create", description: "Create artifacts, versions, and relationships" },
  { key: "artifact:view", description: "View artifacts, versions, relationships, and provenance" },
  { key: "requirement:create", description: "Create requirements" },
  { key: "requirement:edit", description: "Edit requirements" },
  { key: "requirement:view", description: "View requirements" },
  { key: "design:create", description: "Create designs" },
  { key: "design:edit", description: "Edit designs" },
  { key: "design:view", description: "View designs" },
  { key: "code:view", description: "View code artifacts" },
  { key: "code:review", description: "Review code" },
  { key: "test:create", description: "Create tests" },
  { key: "test:edit", description: "Edit tests" },
  { key: "test:review", description: "Review tests" },
  { key: "artifact:approve", description: "Approve artifacts" },
  { key: "artifact:reject", description: "Reject artifacts" },
  { key: "artifact:request_changes", description: "Request changes on artifacts" },
  { key: "release:approve", description: "Approve releases" },
  { key: "audit:view", description: "View audit history" },
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number]["key"];

export const DEFAULT_ROLES: Array<{ name: string; description: string; permissions: PermissionKey[] | "all" }> = [
  { name: "administrator", description: "Full system administration", permissions: "all" },
  {
    name: "product_owner",
    description: "Owns requirements and product approval",
    permissions: [
      "requirement:create",
      "requirement:edit",
      "requirement:view",
      "artifact:approve",
      "artifact:reject",
      "artifact:request_changes",
      "identity:user:view",
      "team:view",
      "audit:view",
      "artifact:create",
      "artifact:view",
      "project:create",
      "project:view",
    ],
  },
  {
    name: "product_manager",
    description: "Manages product requirements",
    permissions: ["requirement:edit", "requirement:view", "identity:user:view", "team:view", "artifact:view", "project:view"],
  },
  {
    name: "architect",
    description: "Owns architecture and design",
    permissions: [
      "design:create",
      "design:edit",
      "design:view",
      "code:view",
      "requirement:view",
      "audit:view",
      "artifact:create",
      "artifact:view",
      "artifact:approve",
      "artifact:reject",
      "artifact:request_changes",
      "project:view",
    ],
  },
  {
    name: "developer",
    description: "Implements code and unit tests",
    permissions: [
      "code:view",
      "code:review",
      "test:create",
      "requirement:view",
      "design:view",
      "artifact:create",
      "artifact:view",
      "project:view",
    ],
  },
  {
    name: "qa_reviewer",
    description: "Reviews and approves tests",
    permissions: [
      "test:create",
      "test:edit",
      "test:review",
      "artifact:approve",
      "artifact:reject",
      "artifact:request_changes",
      "requirement:view",
      "artifact:create",
      "artifact:view",
      "project:view",
    ],
  },
  {
    name: "engineering_manager",
    description: "Engineering review and release authority",
    permissions: [
      "code:review",
      "artifact:approve",
      "artifact:reject",
      "artifact:request_changes",
      "release:approve",
      "audit:view",
      "identity:user:view",
      "artifact:view",
      "project:view",
    ],
  },
  {
    name: "security_reviewer",
    description: "Security review authority",
    permissions: [
      "code:review",
      "artifact:approve",
      "artifact:reject",
      "artifact:request_changes",
      "audit:view",
      "artifact:view",
    ],
  },
  {
    name: "compliance_reviewer",
    description: "Compliance review authority",
    permissions: ["audit:view", "artifact:approve", "requirement:view", "artifact:view"],
  },
  {
    name: "release_manager",
    description: "Release approval authority",
    permissions: ["release:approve", "audit:view", "artifact:view", "project:view"],
  },
  {
    name: "sre",
    description: "Reliability and operations",
    permissions: ["code:view", "audit:view", "artifact:view", "project:view"],
  },
];
